import Vue from 'vue'
import Vuex from 'vuex'
import mutations from './mutations'
import actions from './actions'

Vue.use(Vuex);

const  state = {
         datalist:[
             {
                 title:"任务1",
                 children:[
                     {
                         title:"11111",
                         children:[
                             {
                                 summary:"photo",
                                 finish:0,
                                 time:"2016-12-16",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo2",
                                 finish:0,
                                 time:"2016-12-15",
                                 contitle:"我是标题4",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo3",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题6",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },
                     {
                         title:"88888",
                         children:[
                             {
                                 summary:"photo4",
                                 finish:1,
                                 time:"2016-12-16",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo5",
                                 finish:0,
                                 time:"2016-12-15",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo6",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },

                 ]
             },
             {
                 title:"任务2",
                 children:[
                     {
                         title:"22222",
                         children:[
                             {
                                 summary:"phot7o",
                                 finish:1,
                                 time:"2016-12-16",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"phot32",
                                 finish:0,
                                 time:"2016-12-15",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo9",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },
                     {
                         title:"33333",
                         children:[
                             {
                                 summary:"photo10",
                                 finish:1,
                                 time:"2016-12-16",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo20",
                                 finish:0,
                                 time:"2016-12-15",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo30",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },
                     {
                         title:"44444",
                         children:[
                             {
                                 summary:"photo40",
                                 finish:1,
                                 time:"2016-12-16",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo25",
                                 finish:0,
                                 time:"2016-12-15",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo34",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },

                 ]
             },
             {
                 title:"任务3",
                 children:[
                     {
                         title:"5555",
                         children:[
                             {
                                 summary:"photo25",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo286",
                                 finish:0,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo387",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },
                     {
                         title:"66666",
                         children:[
                             {
                                 summary:"photo88",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo299",
                                 finish:0,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo3546",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },
                     {
                         title:"77777",
                         children:[
                             {
                                 summary:"photo88",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo777",
                                 finish:0,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             },
                             {
                                 summary:"photo999",
                                 finish:1,
                                 time:"2016-12-13",
                                 contitle:"我是标题1",
                                 content:"散落在指尖的阳光，我试着轻轻抓住光影的踪迹，它却在眉宇间投下一片淡淡的阴影。"
                             }
                         ],
                     },
                 ]
             },
         ],
         clicknum:[0,0],
         tasklistnum:[0]

}


export  default  new  Vuex.Store({
    state,
    mutations,
    actions
})